const LANGUAGE_DATA = {
  hu: {
    "app.title": "ShiftPoint",
    "app.subtitle": "Érkezés és távozás kezelése",

    "menu.scan": "Kézi bejegyzés",
    "menu.employees": "Dolgozók",
    "menu.cards": "Kártyák nyomtatása",
    "menu.currentlyInside": "Bent lévők",
    "menu.attendanceList": "Jelenléti lista",
    "menu.employeeProfile": "Dolgozói adatlap",
    "menu.statistics": "Vezetői áttekintés",
    "menu.exportImport": "Export / Import",
    "menu.settings": "Beállítások",
    "menu.groupWork": "Napi munka",
    "menu.groupEmployees": "Dolgozók",
    "menu.groupReports": "Kimutatások",
    "menu.groupSystem": "Rendszer",
    "menu.monthlyAccounting": "Havi elszámolás",
    "menu.vacationTracker": "Szabadságkövető",
    "dashboard.insideNow": "Bent most",
    "dashboard.todayEvents": "Mai események",
    "dashboard.openDays": "Nyitott napok",
    "dashboard.activeEmployees": "Aktív dolgozók",

    "common.actions": "Műveletek",
    "common.edit": "Szerkesztés",
    "common.delete": "Törlés",
    "common.yes": "Igen",
    "common.no": "Nem",

    "scan.title": "Kézi bejegyzés",
    "scan.description": "Dolgozói kód kézi rögzítése érkezéshez vagy távozáshoz.",
    "scan.placeholder": "QR-olvasó helye",
    "scan.startCamera": "Kamera indítása",
    "scan.stopCamera": "Kamera leállítása",
    "scan.switchToFrontCamera": "Elülső kamera használata",
    "scan.switchToBackCamera": "Hátsó kamera használata",
    "scan.openStandalone": "Scan terminál megnyitása",
    "scan.checkIn": "Bejelentkezés",
    "scan.checkOut": "Kijelentkezés",
    "scan.cancel": "Mégse",
    "scan.showQrCode": "Mutasd a QR-kódot a kamerának",
    "scan.scanForIn": "Bejelentkezés – mutasd a QR-kódot",
    "scan.scanForOut": "Kijelentkezés – mutasd a QR-kódot",
    "scan.checkedIn": "Sikeresen bejelentkeztél",
    "scan.checkedOut": "Sikeresen kijelentkeztél",
    "scan.operationFailed": "Sikertelen művelet",
    "scan.serverSaveFailed": "A szerverre mentés sikertelen. Próbáld újra.",
    "scan.alreadyCheckedIn": "Már be vagy jelentkezve",
    "scan.alreadyCheckedOut": "Már ki vagy jelentkezve",
    "scan.manualLabel": "Dolgozói kód",
    "scan.manualPlaceholder": "Pl. EMP-001",
    "scan.manualButton": "Bejegyzés mentése",
    "scan.statusReady": "Írd be a dolgozói kódot.",
    "scan.cameraRunning": "Kamera elindítva. Mutasd a QR-kódot a kamerának.",
    "scan.cameraStopped": "Kamera leállítva.",
    "scan.cameraTimeout": "Nem történt beolvasás. A kamera leállt.",
    "scan.cameraError": "A kamerát nem sikerült elindítani. Ellenőrizd az engedélyt és a HTTPS kapcsolatot.",
    "scan.secureContextError": "A kamera file:// módban nem működik. HTTPS vagy fejlesztői szerver szükséges.",
    "scan.barcodeUnsupported": "Ez a böngésző nem támogatja a natív QR-olvasást.",
    "scan.codeRead": "QR-kód beolvasva.",
    "scan.codeNotFound": "Ehhez a kódhoz nincs dolgozó.",
    "scan.unknownCode": "Ismeretlen dolgozói kód",
    "scan.sourceCamera": "Kamera",
    "scan.sourceUsb": "USB QR olvasó",
    "scan.sourceManual": "Kézi teszt",
    "scan.noResultTitle": "Nincs rögzített dolgozó",
    "scan.noResultText": "Írd be a dolgozói kódot, majd mentsd a bejegyzést.",
    "kiosk.subtitle": "Jelenléti kiosk",
    "kiosk.readyTitle": "Olvasásra kész",
    "kiosk.readyText": "Tartsa a QR kódot az olvasó elé.",
    "kiosk.checkedIn": "Bejelentkezve",
    "kiosk.checkedOut": "Kijelentkezve",

    "employees.title": "Dolgozók",
    "employees.description": "Itt lehet dolgozókat hozzáadni és kezelni.",
    "employees.empty": "Még nincs felvitt dolgozó.",

    "employee.code": "Dolgozói kód",
    "employee.name": "Név",
    "employee.namePlaceholder": "Dolgozó neve",
    "employee.department": "Részleg",
    "employee.departmentPlaceholder": "Pl. Gyártás",
    "employee.active": "Aktív dolgozó",
    "employee.lunchBreakEnabled": "Ebédszünet levonása",
    "employee.lunchBreakShort": "Ebédszünet",
    "employee.inactive": "Inaktív",
    "employee.status": "Állapot",
    "employee.note": "Megjegyzés",
    "employee.notePlaceholder": "Megjegyzés",
    "employee.save": "Dolgozó mentése",
    "employee.new": "Új dolgozó",
    "employee.updated": "Dolgozó frissítve.",
    "employee.saved": "Dolgozó mentve.",
    "employee.deleted": "Dolgozó törölve.",
    "employee.nameRequired": "A dolgozó nevét kötelező kitölteni.",
    "employee.deleteConfirm": "Biztosan törlöd ezt a dolgozót?",

    "cards.title": "Kártyák nyomtatása",
    "cards.description": "Kétoldalas 32 × 46 mm-es betétek: QR-oldal és fekvő adatoldal.",
    "cards.refresh": "Kártyák frissítése",
    "cards.print": "Kártyák nyomtatása",
    "cards.selectAll": "Összes kijelölése",
    "cards.clearSelection": "Kijelölés törlése",
    "cards.noSelection": "Válassz ki legalább egy dolgozói kártyát.",
    "cards.onlyActive": "Csak az aktív dolgozókhoz készül kártya.",
    "cards.empty": "Nincs aktív dolgozó. Eloször adj hozzá dolgozót a Dolgozók oldalon.",
    "cards.cardTitle": "Jelenléti kártya",
    "cards.qrInfo": "QR-kódos belépokártya",
    "cards.printError": "A nyomtatási ablak nem nyílt meg. Ellenőrizd, hogy a böngésző nem blokkolta-e.",

    "inside.title": "Bent lévők",
    "inside.description": "Itt látszik majd, hogy jelenleg kik vannak bent.",

    "inside.empty": "Jelenleg senki nincs bent.",
    "inside.summary": "Bent lévők",
    "inside.refresh": "Frissítés",
    "inside.arrivalTime": "Érkezés ideje",
    "inside.lastEvent": "Utolsó esemény",

    "attendance.in": "Érkezés",
    "attendance.out": "Távozás",
    "attendance.date": "Dátum",
    "attendance.search": "Keresés",
    "attendance.searchPlaceholder": "Név, kód vagy részleg",
    "attendance.today": "Mai nap",
    "attendance.printDaily": "PDF / Nyomt.",
    "attendance.exportDailyXlsx": "XLSX",
    "attendance.printWeekly": "PDF / Nyomt.",
    "attendance.exportWeeklyXlsx": "XLSX",
    "attendance.printMonthly": "PDF / Nyomt.",
    "attendance.exportMonthlyXlsx": "XLSX",
    "attendance.exportPanelTitle": "Export / nyomtatás",
    "attendance.exportGroupDaily": "Napi",
    "attendance.exportGroupWeekly": "Heti",
    "attendance.exportGroupMonthly": "Havi",
    "attendance.viewMode": "Nézet",
    "attendance.viewDaily": "Napi",
    "attendance.viewWeekly": "Heti",
    "attendance.viewMonthly": "Havi",
    "attendance.empty": "Nincs jelenléti esemény ezen a napon.",
    "attendance.savedIn": "Érkezés mentve.",
    "attendance.savedOut": "Távozás mentve.",
    "attendance.inactiveNotSaved": "Inaktív dolgozóhoz nem mentünk jelenlétet.",
    "attendance.eventType": "Típus",
    "attendance.time": "Ido",
    "attendance.source": "Forrás",
    "attendance.employee": "Dolgozó",
    "attendance.code": "Kód",
    "attendance.department": "Részleg",

    "attendance.dailySummaryTitle": "Napi összesítés dolgozónként",
    "attendance.periodSummaryTitle": "Idoszak összesítés dolgozónként",
    "attendance.workDays": "Jelenléti napok",
    "attendance.openDays": "Nyitott napok",
    "attendance.firstArrival": "Kezdés ido",
    "attendance.lastDeparture": "Távozási ido",
    "attendance.rawWorked": "Idotartam",
    "attendance.lunchDeduction": "Ebédszünet",
    "attendance.netWorked": "Ledolgozott ido",
    "attendance.overtime": "Túlóra",
    "attendance.missing": "Hiány",
    "attendance.balance": "Eltérés",
    "attendance.dayStatus": "Állapot",
    "attendance.noSummary": "Nincs napi összesítés ezen a napon.",
    "attendance.noPeriodRows": "Nincs megjeleníthető napi bontás ebben az időszakban.",
    "attendance.noPeriodSummary": "Nincs időszaki összesítés ebben az időszakban.",
    "attendance.statusClosed": "Lezárva",
    "attendance.statusOpen": "Folyamatban",
    "attendance.statusIncomplete": "Hiányos",
    "attendance.openDayWarningOne": "Figyelem: {count} dolgozónál nincs távozás rögzítve.",
    "attendance.openDayWarningMany": "Figyelem: {count} dolgozónál nincs távozás rögzítve.",

    "attendance.editBoxTitle": "Napi érkezés és távozás javítása",
    "attendance.saveCorrection": "Érkezés és távozás mentése",
    "attendance.eventsToCorrect": "Javítandó események",
    "attendance.addArrival": "+ Érkezés hozzáadása",
    "attendance.addDeparture": "+ Távozás hozzáadása",
    "attendance.cancelCorrection": "Mégse",
    "attendance.eventUpdated": "Az érkezési és távozási ido mentve.",
    "attendance.invalidTimeRange": "A távozási ido legyen késobbi az érkezési idonél.",
    "attendance.invalidTimeFormat": "Az időt 24 órás ÓÓ:PP formában add meg, például 15:30.",
    "attendance.eventDeleted": "Jelenléti esemény törölve.",
    "attendance.deleteConfirm": "Biztosan törlöd ezt a jelenléti eseményt?",
    "attendance.eventRequired": "Válassz ki egy javítandó eseményt.",

    "attendance.title": "Jelenléti lista",
    "attendance.description": "Itt lesz a napi, heti és havi jelenléti lista.",

    "profile.title": "Dolgozói adatlap",
    "profile.description": "Személyenkénti havi jelenléti összesítő.",
    "profile.employee": "Dolgozó",
    "profile.search": "Dolgozó keresése",
    "profile.searchPlaceholder": "Név, kód vagy részleg",
    "profile.noSearchResults": "Nincs találat",
    "profile.month": "Hónap",
    "profile.refresh": "Frissítés",
    "profile.printPdf": "Személy PDF / Nyomtatás",
    "profile.exportXlsx": "Személy XLSX export",
    "profile.selectEmployee": "Válassz dolgozót",
    "profile.noEmployees": "Nincs felvitt dolgozó",
    "profile.noData": "Nincs jelenléti adat ebben a hónapban.",
    "profile.workDays": "Jelenléti napok",
    "profile.totalWorked": "Összes ledolgozott ido",
    "profile.totalBalance": "Összes eltérés",
    "profile.openDays": "Folyamatban lévo napok",
    "profile.dailyRowsTitle": "Napi bontás",
    "profile.eventRowsTitle": "Napi ki-be mozgások",
    "profile.eventNumber": "Sorszám",
    "profile.noEvents": "Nincs ki-be mozgás ebben a hónapban.",

    "statistics.title": "Vezetői áttekintés",
    "statistics.description": "Napi állapotok és ellenorzést igénylo bejegyzések.",
    "statistics.date": "Dátum",
    "statistics.today": "Mai nap",
    "statistics.refresh": "Frissítés",
    "statistics.totalEmployees": "Összes dolgozó",
    "statistics.activeEmployees": "Aktív dolgozó",
    "statistics.employeesWithEvents": "Érintett dolgozók",
    "statistics.currentlyInside": "Jelenleg bent",
    "statistics.closedDays": "Lezárt napok",
    "statistics.openDays": "Folyamatban",
    "statistics.totalWorked": "Összes ledolgozott ido",
    "statistics.totalBalance": "Összes eltérés",
    "statistics.dailyTableTitle": "Aktív dolgozók napi állapota",
    "statistics.noData": "Nincs jelenléti adat ezen a napon.",
    "statistics.arrived": "Megérkezett",
    "statistics.leftToday": "Távozott",
    "statistics.absentToday": "Igazolt távollét",
    "statistics.notArrived": "Nem érkezett meg",
    "statistics.needsAttention": "Ellenorzést igényel",
    "statistics.attentionTitle": "Figyelmet igényel",
    "statistics.issue": "Ellenorizendo",
    "statistics.noIssues": "Nincs ellenorzést igénylo bejegyzés.",
    "statistics.statusInside": "Bent van",
    "statistics.statusLeft": "Távozott",
    "statistics.statusAbsent": "Távollét",
    "statistics.statusNotArrived": "Nem érkezett meg",
    "statistics.statusNoEntry": "Nincs bejegyzés",
    "statistics.invalidOrder": "Hibás érkezési/távozási sorrend",
    "statistics.absenceConflict": "Távollét és jelenléti bejegyzés ugyanazon a napon",
    "statistics.forgottenDeparture": "Valószínuleg elfelejtett távozás",
    "statistics.shortWorkday": "Rövid lezárt munkanap",
    "statistics.noArrivalOrAbsence": "Nincs érkezés és nincs távollét rögzítve",
    "statistics.statusDayOff": "Szabadnap",
    "statistics.upcomingAbsences": "Aktuális és közelgo távollétek",
    "statistics.noUpcomingAbsences": "A következo 7 napra nincs távollét rögzítve.",
    "statistics.monthlyLeaders": "Havi kiemelt eltérések",
    "statistics.mostOvertime": "Legtöbb túlóra",
    "statistics.mostMissing": "Legtöbb hiány",
    "statistics.noRankingData": "Nincs megjelenítheto adat.",

    "monthly.title": "Havi elszámolás",
    "monthly.description": "100+ dolgozó havi áttekintése ledolgozott idővel, túlórával, kajapénzzel és távollétekkel.",
    "monthly.summaryTitle": "Havi fo áttekintés",
    "monthly.detailTitle": "Dolgozó havi részletei",
    "monthly.absenceFormTitle": "Távollét rögzítése",
    "monthly.absenceListTitle": "Havi távollétek",
    "monthly.details": "Részletek",
    "monthly.noRows": "Nincs megjelenítheto dolgozó ebben a nézetben.",
    "monthly.noDetails": "Nincs jelenléti vagy távolléti adat ehhez a dolgozóhoz ebben a hónapban.",
    "monthly.selectEmployee": "Válassz dolgozót a havi fotáblából.",

    "vacation.title": "Szabadságkövető",
    "vacation.description": "Éves szabadságkeretek, kivett és lefoglalt napok követése.",
    "vacation.year": "Év",
    "vacation.allDepartments": "Minden részleg",
    "vacation.allowanceTitle": "Éves szabadságkeret beállítása",
    "vacation.entitled": "Éves keret",
    "vacation.carried": "Áthozott napok",
    "vacation.available": "Összes rendelkezésre áll",
    "vacation.used": "Kivett napok",
    "vacation.booked": "Lefoglalt napok",
    "vacation.remaining": "Megmaradt napok",
    "vacation.nextDate": "Következő szabadság",
    "vacation.saveAllowance": "Keret mentése",
    "vacation.statusReady": "A szabadságköveto készen áll.",
    "vacation.saved": "A szabadságkeret mentve.",
    "vacation.invalidAllowance": "Válassz dolgozót, és adj meg érvényes, nem negatív napértékeket.",
    "vacation.overviewTitle": "Dolgozói szabadságkeretek",
    "vacation.detailsTitle": "Szabadságok részletei",
    "vacation.workdays": "Elszámolt munkanapok",
    "vacation.periodStatus": "Állapot",
    "vacation.usedStatus": "Kivett",
    "vacation.bookedStatus": "Lefoglalt",
    "vacation.currentStatus": "Folyamatban",
    "vacation.noRows": "Nincs megjelenítheto dolgozó.",
    "vacation.noDetails": "Ehhez a dolgozóhoz nincs szabadság rögzítve ebben az évben.",
    "vacation.selectEmployee": "Válassz dolgozót a táblából.",

    "absence.startDate": "Kezdo dátum",
    "absence.endDate": "Záró dátum",
    "absence.type": "Távollét típusa",
    "absence.sick": "Betegség",
    "absence.vacation": "Szabadság",
    "absence.excused": "Igazolt hiányzás",
    "absence.unexcused": "Igazolatlan hiányzás",
    "absence.unpaid": "Fizetés nélküli",
    "absence.other": "Egyéb",
    "absence.sickShort": "Beteg",
    "absence.vacationShort": "Szabi",
    "absence.excusedShort": "Igazolt",
    "absence.unexcusedShort": "Igazolatlan",
    "absence.unpaidShort": "Fiz. nélk.",
    "absence.otherShort": "Egyéb",
    "absence.totalDays": "Távollét napok",
    "absence.save": "Távollét mentése",
    "absence.invalid": "Válassz dolgozót és érvényes dátumtartományt.",
    "absence.empty": "Nincs távollét rögzítve erre a hónapra.",
    "absence.deleteConfirm": "Biztosan törlöd ezt a távollétet?",

    "export.title": "Export / Import",
    "export.description": "JSON biztonsági mentés és visszatöltés localStorage adatokhoz.",
    "export.jsonTitle": "JSON mentés / visszatöltés",
    "export.jsonDescription": "A JSON mentés tartalmazza a beállításokat, dolgozókat és jelenléti eseményeket.",
    "export.importWarning": "Figyelem: visszatöltéskor a jelenlegi adatok felülíródnak.",
    "export.downloadJson": "JSON mentés letöltése",
    "export.xlsxSaved": "XLSX export letöltve.",
    "export.xlsxError": "Az XLSX export sikertelen.",
    "export.importJson": "JSON visszatöltése",
    "export.statusReady": "Export / Import készen áll.",
    "export.summarySettings": "Beállítások",
    "export.summaryEmployees": "Dolgozók",
    "export.summaryEvents": "Jelenléti események",
    "export.saved": "JSON mentés letöltve.",
    "export.importNoFile": "Nincs kiválasztott JSON fájl.",
    "export.importInvalid": "Hibás vagy nem megfelelo JSON fájl.",
    "export.importConfirm": "Biztosan visszatöltöd ezt a mentést? A jelenlegi adatok felülíródnak.",
    "export.importSuccess": "JSON mentés sikeresen visszatöltve.",
    "export.importError": "A JSON visszatöltése sikertelen.",

    "print.dailyAttendanceTitle": "Napi jelenléti lista",
    "print.weeklyAttendanceTitle": "Heti jelenléti lista",
    "print.weekRange": "Heti időszak",
    "print.weeklySummary": "Heti összesítés dolgozónként",
    "print.monthlyAttendanceTitle": "Havi jelenléti lista",
    "print.employeeAttendanceTitle": "Személyenkénti jelenléti lap",
    "print.employeePeriod": "Időszak",
    "print.employeeSummary": "Személy összesítés",
    "print.employeeDailyBreakdown": "Napi bontás",
    "print.employeeNoData": "Nincs jelenléti adat ennél a dolgozónál ebben a hónapban.",
    "print.monthRange": "Havi időszak",
    "print.monthlySummary": "Havi összesítés dolgozónként",
    "print.monthlyDailyBreakdown": "Napi bontás a hónapban",
    "print.noMonthlySummary": "Nincs havi jelenléti adat ebben az időszakban.",
    "print.weeklyDailyBreakdown": "Napi bontás a héten",
    "print.workDays": "Jelenléti napok",
    "print.openDays": "Folyamatban lévő napok",
    "print.awayTime": "Távolléti idő",
    "print.noWeeklySummary": "Nincs heti jelenléti adat ebben az időszakban.",
    "print.generatedAt": "Nyomtatás ideje",
    "print.company": "Cég",
    "print.dailyEvents": "Napi események",
    "print.dailySummary": "Napi összesítés dolgozónként",
    "print.noEvents": "Nincs jelenléti esemény ezen a napon.",
    "print.noSummary": "Nincs napi összesítés ezen a napon.",
    "print.printError": "A nyomtatási ablak nem nyílt meg. Ellenorizd, hogy a böngészo nem blokkolta-e.",

    "settings.title": "Beállítások",
    "settings.companyName": "Cég neve",
    "settings.dailyNorm": "Napi norma",
    "settings.lunchBreak": "Ebédszünet",
    "settings.overtimeHourlyRate": "Túlóra óradíj (lej/óra)",
    "settings.showOvertimeData": "Túlóra és túlórapénz megjelenítése",
    "settings.mealVoucherDailyValue": "Kajabon érték (lej/nap)",
    "settings.storageMode": "Mentési mód",
    "settings.save": "Beállítások mentése",
    "settings.reset": "Alapértékek visszaállítása",
    "settings.statusReady": "Beállítások készen állnak.",
    "settings.saved": "Beállítások mentve.",
    "settings.resetDone": "Alapértékek visszaállítva.",
    "settings.invalidDailyNorm": "A napi norma legyen legalább 01:00.",
    "settings.invalidLunchBreak": "Az ebédszünet nem lehet nagyobb, mint a napi norma.",
    "settings.invalidPaymentValues": "Az óradíj és a kajabon értéke nem lehet negatív.",

    "payment.overtimeRate": "Túlóra óradíj",
    "payment.overtimeValue": "Túlóra érték",
    "payment.mealVoucherDailyValue": "Kajabon napi érték",
    "payment.mealVoucherDays": "Kajabon napok",
    "payment.mealVoucherValue": "Kajabon érték",
    "payment.totalPayment": "Összes fizetendo",
    "absence.allActiveEmployees": "Összes aktív dolgozó",
    "calendar.title": "Céges munkanaptár",
    "calendar.dayType": "Nap típusa",
    "calendar.dayOff": "Szabadnap",
    "calendar.vacation": "Szabadság",
    "calendar.save": "Idoszak mentése",
    "calendar.invalid": "Válassz érvényes kezdo és záró dátumot.",
    "calendar.empty": "Ebben a hónapban nincs céges szabadnap vagy szabadság.",
    "calendar.deleteConfirm": "Biztosan törlöd ezt az időszakot?",

    "backup.closeWarning": "Bezárás elott az adatok automatikusan mentésre kerülnek.",
    "backup.restoreAutoBackup": "Automatikus mentés visszaállítása",
    "backup.restoreConfirm": "Biztosan visszaállítod az utolsó automatikus mentést? A jelenlegi adatok felülíródnak.",
    "backup.restoreMissing": "Nincs elérheto automatikus mentés.",
    "backup.restoreInvalid": "Az automatikus mentés hibás vagy nem olvasható.",
    "backup.restoreSuccess": "Automatikus mentés sikeresen visszaállítva.",
    "backup.restoreError": "Az automatikus mentés visszaállítása sikertelen.",
  },

  ro: {
    "app.title": "ShiftPoint",
    "app.subtitle": "Gestionarea sosirilor și plecărilor",

    "menu.scan": "Înregistrare manuală",
    "menu.employees": "Angajați",
    "menu.cards": "Tipărire carduri",
    "menu.currentlyInside": "Prezenți acum",
    "menu.attendanceList": "Lista pontaj",
    "menu.employeeProfile": "Fișa angajat",
    "menu.statistics": "Prezentare manager",
    "menu.exportImport": "Export / Import",
    "menu.settings": "Setari",
    "menu.groupWork": "Lucru zilnic",
    "menu.groupEmployees": "Angajați",
    "menu.groupReports": "Rapoarte",
    "menu.groupSystem": "Sistem",
    "menu.monthlyAccounting": "Calcul lunar",
    "menu.vacationTracker": "Evidența concedii",
    "dashboard.insideNow": "Înauntru acum",
    "dashboard.todayEvents": "Evenimente azi",
    "dashboard.openDays": "Zile deschise",
    "dashboard.activeEmployees": "Angajați activi",

    "common.actions": "Acțiuni",
    "common.edit": "Editare",
    "common.delete": "Ștergere",
    "common.yes": "Da",
    "common.no": "Nu",

    "scan.title": "Înregistrare manuală",
    "scan.description": "Introducerea manuală a codului angajatului pentru intrare sau ieșire.",
    "scan.placeholder": "Loc pentru cititorul QR",
    "scan.startCamera": "Pornește camera",
    "scan.stopCamera": "Oprește camera",
    "scan.switchToFrontCamera": "Folosește camera frontală",
    "scan.switchToBackCamera": "Folosește camera din spate",
    "scan.openStandalone": "Deschide terminalul Scan",
    "scan.checkIn": "Intrare",
    "scan.checkOut": "Ieșire",
    "scan.cancel": "Anulează",
    "scan.showQrCode": "Arată codul QR camerei",
    "scan.scanForIn": "Intrare – arată codul QR",
    "scan.scanForOut": "Ieșire – arată codul QR",
    "scan.checkedIn": "Intrare înregistrată cu succes",
    "scan.checkedOut": "Ieșire înregistrată cu succes",
    "scan.operationFailed": "Operațiune nereușită",
    "scan.serverSaveFailed": "Salvarea pe server a eșuat. Încearcă din nou.",
    "scan.alreadyCheckedIn": "Ești deja înregistrat la intrare",
    "scan.alreadyCheckedOut": "Ești deja înregistrat la ieșire",
    "scan.manualLabel": "Cod angajat",
    "scan.manualPlaceholder": "Ex. EMP-001",
    "scan.manualButton": "Salvează înregistrarea",
    "scan.statusReady": "Introdu codul angajatului.",
    "scan.cameraRunning": "Camera este pornită. Arată codul QR către cameră.",
    "scan.cameraStopped": "Camera a fost oprită.",
    "scan.cameraTimeout": "Nu a fost scanat niciun cod. Camera s-a oprit.",
    "scan.cameraError": "Camera nu a putut fi pornită. Verifică permisiunea și conexiunea HTTPS.",
    "scan.secureContextError": "Camera nu funcționează în modul file://. Este necesar HTTPS sau server de test.",
    "scan.barcodeUnsupported": "Acest browser nu suportă citirea QR nativă.",
    "scan.codeRead": "Cod QR scanat.",
    "scan.codeNotFound": "Nu există angajat pentru acest cod.",
    "scan.unknownCode": "Cod angajat necunoscut",
    "scan.sourceCamera": "Camera",
    "scan.sourceUsb": "Cititor QR USB",
    "scan.sourceManual": "Test manual",
    "scan.noResultTitle": "Niciun angajat înregistrat",
    "scan.noResultText": "Introdu codul angajatului și salvează înregistrarea.",
    "kiosk.subtitle": "Kiosk de pontaj",
    "kiosk.readyTitle": "Gata de citire",
    "kiosk.readyText": "Apropie codul QR de cititor.",
    "kiosk.checkedIn": "Intrare înregistrată",
    "kiosk.checkedOut": "Ieșire înregistrată",

    "employees.title": "Angajați",
    "employees.description": "Aici se pot adăuga și gestiona angajații.",
    "employees.empty": "Nu există încă angajați adăugați.",

    "employee.code": "Cod angajat",
    "employee.name": "Nume",
    "employee.namePlaceholder": "Numele angajatului",
    "employee.department": "Departament",
    "employee.departmentPlaceholder": "Ex. Producție",
    "employee.active": "Angajat activ",
    "employee.lunchBreakEnabled": "Scade pauza de masa",
    "employee.lunchBreakShort": "Pauza masa",
    "employee.inactive": "Inactiv",
    "employee.status": "Stare",
    "employee.note": "Nota",
    "employee.notePlaceholder": "Nota",
    "employee.save": "Salveaza angajatul",
    "employee.new": "Angajat nou",
    "employee.updated": "Angajat actualizat.",
    "employee.saved": "Angajat salvat.",
    "employee.deleted": "Angajat șters.",
    "employee.nameRequired": "Numele angajatului este obligatoriu.",
    "employee.deleteConfirm": "Sigur ștergi acest angajat?",

    "cards.title": "Tipărire carduri",
    "cards.description": "Inserții față-verso 32 × 46 mm: cod QR și informații în format orizontal.",
    "cards.refresh": "Actualizeaza cardurile",
    "cards.print": "Tipărește cardurile",
    "cards.selectAll": "Selecteaza toate",
    "cards.clearSelection": "Șterge selecția",
    "cards.noSelection": "Selectează cel puțin un card de angajat.",
    "cards.onlyActive": "Cardurile se creează doar pentru angajații activi.",
    "cards.empty": "Nu există angajați activi. Adaugă mai întâi un angajat în pagina Angajați.",
    "cards.cardTitle": "Card de pontaj",
    "cards.qrInfo": "Card de acces cu cod QR",
    "cards.printError": "Fereastra de tipărire nu s-a deschis. Verifică dacă browserul a blocat-o.",

    "inside.title": "Prezenți acum",
    "inside.description": "Aici se va vedea cine este prezent în acest moment.",

    "inside.empty": "Momentan nu este nimeni prezent.",
    "inside.summary": "Prezenți acum",
    "inside.refresh": "Actualizare",
    "inside.arrivalTime": "Ora sosirii",
    "inside.lastEvent": "Ultimul eveniment",

    "attendance.in": "Sosire",
    "attendance.out": "Plecare",
    "attendance.date": "Data",
    "attendance.search": "Căutare",
    "attendance.searchPlaceholder": "Nume, cod sau departament",
    "attendance.today": "Astăzi",
    "attendance.printDaily": "PDF / Print",
    "attendance.exportDailyXlsx": "XLSX",
    "attendance.printWeekly": "PDF / Print",
    "attendance.exportWeeklyXlsx": "XLSX",
    "attendance.printMonthly": "PDF / Print",
    "attendance.exportMonthlyXlsx": "XLSX",
    "attendance.exportPanelTitle": "Export / tipărire",
    "attendance.exportGroupDaily": "Zilnic",
    "attendance.exportGroupWeekly": "Săptămânal",
    "attendance.exportGroupMonthly": "Lunar",
    "attendance.viewMode": "Vizualizare",
    "attendance.viewDaily": "Zilnic",
    "attendance.viewWeekly": "Săptămânal",
    "attendance.viewMonthly": "Lunar",
    "attendance.empty": "Nu există evenimente de pontaj pentru această zi.",
    "attendance.savedIn": "Sosire salvată.",
    "attendance.savedOut": "Plecare salvată.",
    "attendance.inactiveNotSaved": "Nu se salvează pontaj pentru angajat inactiv.",
    "attendance.eventType": "Tip",
    "attendance.time": "Ora",
    "attendance.source": "Sursă",
    "attendance.employee": "Angajat",
    "attendance.code": "Cod",
    "attendance.department": "Departament",

    "attendance.dailySummaryTitle": "Total zilnic pe angajat",
    "attendance.periodSummaryTitle": "Total pe perioada pe angajat",
    "attendance.workDays": "Zile cu pontaj",
    "attendance.openDays": "Zile deschise",
    "attendance.firstArrival": "Ora începerii",
    "attendance.lastDeparture": "Ora plecarii",
    "attendance.rawWorked": "Durata",
    "attendance.lunchDeduction": "Pauza masa",
    "attendance.netWorked": "Timp lucrat",
    "attendance.overtime": "Ore suplimentare",
    "attendance.missing": "Lipsa",
    "attendance.balance": "Diferență",
    "attendance.dayStatus": "Stare",
    "attendance.noSummary": "Nu exista total zilnic pentru aceasta zi.",
    "attendance.noPeriodRows": "Nu exista defalcare zilnica pentru aceasta perioada.",
    "attendance.noPeriodSummary": "Nu exista total pe perioada pentru aceasta perioada.",
    "attendance.statusClosed": "Închis",
    "attendance.statusOpen": "În desfășurare",
    "attendance.statusIncomplete": "Incomplet",
    "attendance.openDayWarningOne": "Atenție: la {count} angajat nu este înregistrata plecarea.",
    "attendance.openDayWarningMany": "Atenție: la {count} angajați nu este înregistrata plecarea.",

    "attendance.editBoxTitle": "Corectare sosire și plecare zilnică",
    "attendance.saveCorrection": "Salveaza sosirea și plecarea",
    "attendance.eventsToCorrect": "Evenimente de corectat",
    "attendance.addArrival": "+ Adauga sosire",
    "attendance.addDeparture": "+ Adauga plecare",
    "attendance.cancelCorrection": "Anuleaza",
    "attendance.eventUpdated": "Ora sosirii și plecării a fost salvată.",
    "attendance.invalidTimeRange": "Ora plecării trebuie să fie după ora sosirii.",
    "attendance.invalidTimeFormat": "Introdu ora în format de 24 de ore HH:MM, de exemplu 15:30.",
    "attendance.eventDeleted": "Evenimentul de pontaj a fost șters.",
    "attendance.deleteConfirm": "Sigur ștergi acest eveniment de pontaj?",
    "attendance.eventRequired": "Alege un eveniment pentru corectare.",

    "attendance.title": "Lista pontaj",
    "attendance.description": "Aici va fi lista zilnică, săptămânală și lunară.",

    "profile.title": "Fișa angajat",
    "profile.description": "Total lunar individual pe angajat.",
    "profile.employee": "Angajat",
    "profile.search": "Cauta angajat",
    "profile.searchPlaceholder": "Nume, cod sau departament",
    "profile.noSearchResults": "Niciun rezultat",
    "profile.month": "Luna",
    "profile.refresh": "Actualizare",
    "profile.printPdf": "PDF angajat / Tipărire",
    "profile.exportXlsx": "Export XLSX angajat",
    "profile.selectEmployee": "Alege angajat",
    "profile.noEmployees": "Nu exista angajați",
    "profile.noData": "Nu exista date de pontaj în aceasta luna.",
    "profile.workDays": "Zile cu pontaj",
    "profile.totalWorked": "Total timp lucrat",
    "profile.totalBalance": "Diferență totală",
    "profile.openDays": "Zile în desfășurare",
    "profile.dailyRowsTitle": "Detaliere pe zile",
    "profile.eventRowsTitle": "Mișcări zilnice intrare/ieșire",
    "profile.eventNumber": "Nr.",
    "profile.noEvents": "Nu exista mișcări de intrare/ieșire în aceasta luna.",

    "statistics.title": "Prezentare manager",
    "statistics.description": "Stări zilnice și înregistrări care necesită verificare.",
    "statistics.date": "Data",
    "statistics.today": "Astazi",
    "statistics.refresh": "Actualizare",
    "statistics.totalEmployees": "Total angajați",
    "statistics.activeEmployees": "Angajați activi",
    "statistics.employeesWithEvents": "Angajați cu pontaj",
    "statistics.currentlyInside": "Prezenți acum",
    "statistics.closedDays": "Zile închise",
    "statistics.openDays": "În desfășurare",
    "statistics.totalWorked": "Total timp lucrat",
    "statistics.totalBalance": "Diferență totală",
    "statistics.dailyTableTitle": "Starea zilnică a angajaților activi",
    "statistics.noData": "Nu exista date de pontaj pentru aceasta zi.",
    "statistics.arrived": "Sosiți",
    "statistics.leftToday": "Plecați",
    "statistics.absentToday": "Absență justificată",
    "statistics.notArrived": "Nu au sosit",
    "statistics.needsAttention": "Necesită verificare",
    "statistics.attentionTitle": "Necesită atenție",
    "statistics.issue": "De verificat",
    "statistics.noIssues": "Nu exista înregistrari care necesita verificare.",
    "statistics.statusInside": "Prezent",
    "statistics.statusLeft": "Plecat",
    "statistics.statusAbsent": "Absent",
    "statistics.statusNotArrived": "Nu a sosit",
    "statistics.statusNoEntry": "Fără înregistrare",
    "statistics.invalidOrder": "Ordine invalidă sosire/plecare",
    "statistics.absenceConflict": "Absență și pontaj în aceeași zi",
    "statistics.forgottenDeparture": "Plecare probabil uitată",
    "statistics.shortWorkday": "Zi de lucru închisă prea scurtă",
    "statistics.noArrivalOrAbsence": "Nu exista sosire sau absență înregistrată",
    "statistics.statusDayOff": "Zi liberă",
    "statistics.upcomingAbsences": "Absențe actuale și viitoare",
    "statistics.noUpcomingAbsences": "Nu exista absențe înregistrate pentru următoarele 7 zile.",
    "statistics.monthlyLeaders": "Abateri lunare principale",
    "statistics.mostOvertime": "Cele mai multe ore suplimentare",
    "statistics.mostMissing": "Cel mai mare deficit",
    "statistics.noRankingData": "Nu exista date de afișat.",

    "monthly.title": "Calcul lunar",
    "monthly.description": "Privire lunară pentru 100+ angajați: timp lucrat, ore suplimentare, tichet de masă și absențe.",
    "monthly.summaryTitle": "Privire generală lunară",
    "monthly.detailTitle": "Detalii lunare angajat",
    "monthly.absenceFormTitle": "Înregistrare absență",
    "monthly.absenceListTitle": "Absențe lunare",
    "monthly.details": "Detalii",
    "monthly.noRows": "Nu exista angajați de afișat în această vizualizare.",
    "monthly.noDetails": "Nu exista pontaj sau absențe pentru acest angajat în această lună.",
    "monthly.selectEmployee": "Alege un angajat din tabelul lunar.",

    "vacation.title": "Evidența concedii",
    "vacation.description": "Urmărirea drepturilor anuale, zilelor folosite și planificate.",
    "vacation.year": "An",
    "vacation.allDepartments": "Toate departamentele",
    "vacation.allowanceTitle": "Setarea dreptului anual la concediu",
    "vacation.entitled": "Drept anual",
    "vacation.carried": "Zile reportate",
    "vacation.available": "Total disponibil",
    "vacation.used": "Zile folosite",
    "vacation.booked": "Zile planificate",
    "vacation.remaining": "Zile rămase",
    "vacation.nextDate": "Următorul concediu",
    "vacation.saveAllowance": "Salveaza dreptul",
    "vacation.statusReady": "Evidența concediilor este pregătită.",
    "vacation.saved": "Dreptul la concediu a fost salvat.",
    "vacation.invalidAllowance": "Alege angajatul și introdu valori valide, nenegative.",
    "vacation.overviewTitle": "Drepturile angajaților",
    "vacation.detailsTitle": "Detalii concedii",
    "vacation.workdays": "Zile lucrătoare calculate",
    "vacation.periodStatus": "Stare",
    "vacation.usedStatus": "Folosit",
    "vacation.bookedStatus": "Planificat",
    "vacation.currentStatus": "În desfășurare",
    "vacation.noRows": "Nu exista angajați de afișat.",
    "vacation.noDetails": "Nu exista concedii înregistrate pentru acest angajat în acest an.",
    "vacation.selectEmployee": "Alege un angajat din tabel.",

    "absence.startDate": "Data început",
    "absence.endDate": "Data sfârșit",
    "absence.type": "Tip absență",
    "absence.sick": "Boala",
    "absence.vacation": "Concediu",
    "absence.excused": "Absență motivată",
    "absence.unexcused": "Absență nemotivată",
    "absence.unpaid": "Concediu fără plată",
    "absence.other": "Altul",
    "absence.sickShort": "Boala",
    "absence.vacationShort": "Conc.",
    "absence.excusedShort": "Motivat",
    "absence.unexcusedShort": "Nemot.",
    "absence.unpaidShort": "Fără plată",
    "absence.otherShort": "Altul",
    "absence.totalDays": "Zile absență",
    "absence.save": "Salveaza absență",
    "absence.invalid": "Alege angajatul și un interval de date valid.",
    "absence.empty": "Nu exista absențe înregistrate pentru această lună.",
    "absence.deleteConfirm": "Sigur ștergi această absență?",

    "export.title": "Export / Import",
    "export.description": "Backup și restaurare JSON pentru datele localStorage.",
    "export.jsonTitle": "Backup / restaurare JSON",
    "export.jsonDescription": "Fișierul JSON conține setările, angajații și evenimentele de pontaj.",
    "export.importWarning": "Atenție: la restaurare, datele actuale vor fi suprascrise.",
    "export.downloadJson": "Descarca backup JSON",
    "export.importJson": "Restaureaza JSON",
    "export.statusReady": "Export / Import pregatit.",
    "export.summarySettings": "Setări",
    "export.summaryEmployees": "Angajați",
    "export.summaryEvents": "Evenimente pontaj",
    "export.saved": "Backup JSON descărcat.",
    "export.xlsxSaved": "Export XLSX descărcat.",
    "export.xlsxError": "Exportul XLSX a eșuat.",
    "export.importNoFile": "Nu a fost selectat niciun fișier JSON.",
    "export.importInvalid": "Fișier JSON invalid sau nepotrivit.",
    "export.importConfirm": "Sigur restaurezi acest backup? Datele actuale vor fi suprascrise.",
    "export.importSuccess": "Backup JSON restaurat cu succes.",
    "export.importError": "Restaurarea JSON a eșuat.",

    "print.dailyAttendanceTitle": "Lista zilnică de pontaj",
    "print.weeklyAttendanceTitle": "Lista săptămânală de pontaj",
    "print.weekRange": "Perioada săptămânii",
    "print.weeklySummary": "Total săptămânal pe angajat",
    "print.monthlyAttendanceTitle": "Lista lunară de pontaj",
    "print.employeeAttendanceTitle": "Fișa individuală de pontaj",
    "print.employeePeriod": "Perioada",
    "print.employeeSummary": "Total individual",
    "print.employeeDailyBreakdown": "Detaliere pe zile",
    "print.employeeNoData": "Nu exista date de pontaj pentru acest angajat în această lună.",
    "print.monthRange": "Perioada lunii",
    "print.monthlySummary": "Total lunar pe angajat",
    "print.monthlyDailyBreakdown": "Detaliere zilnică în lună",
    "print.noMonthlySummary": "Nu exista date de pontaj pentru această perioadă lunară.",
    "print.weeklyDailyBreakdown": "Detaliere zilnică în săptămână",
    "print.workDays": "Zile cu pontaj",
    "print.openDays": "Zile în desfășurare",
    "print.awayTime": "Timp absent",
    "print.noWeeklySummary": "Nu exista date de pontaj pentru această perioadă.",
    "print.generatedAt": "Ora tipăririi",
    "print.company": "Firma",
    "print.dailyEvents": "Evenimente zilnice",
    "print.dailySummary": "Total zilnic pe angajat",
    "print.noEvents": "Nu exista evenimente de pontaj pentru această zi.",
    "print.noSummary": "Nu exista total zilnic pentru această zi.",
    "print.printError": "Fereastra de tipărire nu s-a deschis. Verifică dacă browserul a blocat-o.",

    "settings.title": "Setări",
    "settings.companyName": "Numele firmei",
    "settings.dailyNorm": "Norma zilnică",
    "settings.lunchBreak": "Pauza de masă",
    "settings.overtimeHourlyRate": "Tarif ore suplimentare (lei/oră)",
    "settings.showOvertimeData": "Afișează orele suplimentare și valoarea lor",
    "settings.mealVoucherDailyValue": "Valoare tichet masă (lei/zi)",
    "settings.storageMode": "Mod salvare",
    "settings.save": "Salveaza setările",
    "settings.reset": "Restabilește valorile implicite",
    "settings.statusReady": "Setările sunt pregătite.",
    "settings.saved": "Setări salvate.",
    "settings.resetDone": "Valorile implicite au fost restaurate.",
    "settings.invalidDailyNorm": "Norma zilnică trebuie să fie cel puțin 01:00.",
    "settings.invalidLunchBreak": "Pauza de masă nu poate fi mai mare decât norma zilnică.",
    "settings.invalidPaymentValues": "Tariful orar și valoarea tichetului de masă nu pot fi negative.",

    "payment.overtimeRate": "Tarif ore suplimentare",
    "payment.overtimeValue": "Valoare ore suplimentare",
    "payment.mealVoucherDailyValue": "Valoare tichet masă / zi",
    "payment.mealVoucherDays": "Zile tichete masă",
    "payment.mealVoucherValue": "Valoare tichete masă",
    "payment.totalPayment": "Total de plată",
    "absence.allActiveEmployees": "Toți angajații activi",
    "calendar.title": "Calendar de lucru al firmei",
    "calendar.dayType": "Tipul zilei",
    "calendar.dayOff": "Zi liberă",
    "calendar.vacation": "Concediu",
    "calendar.save": "Salveaza perioada",
    "calendar.invalid": "Selecteaza o dată de început și de sfârșit validă.",
    "calendar.empty": "Nu exista zile libere sau concediu comun în această lună.",
    "calendar.deleteConfirm": "Sigur ștergi această perioadă?",

    "backup.closeWarning": "Înainte de închidere, datele sunt salvate automat.",
    "backup.restoreAutoBackup": "Restaureaza backup automat",
    "backup.restoreConfirm": "Sigur restaurezi ultimul backup automat? Datele actuale vor fi suprascrise.",
    "backup.restoreMissing": "Nu exista backup automat disponibil.",
    "backup.restoreInvalid": "Backupul automat este invalid sau nu poate fi citit.",
    "backup.restoreSuccess": "Backup automat restaurat cu succes.",
    "backup.restoreError": "Restaurarea backupului automat a eșuat.",
  },

  en: {
    "app.title": "ShiftPoint",
    "app.subtitle": "Arrival and departure tracking",

    "menu.scan": "Manual entry",
    "menu.employees": "Employees",
    "menu.cards": "Print cards",
    "menu.currentlyInside": "Currently inside",
    "menu.attendanceList": "Attendance list",
    "menu.employeeProfile": "Employee profile",
    "menu.statistics": "Manager overview",
    "menu.exportImport": "Export / Import",
    "menu.settings": "Settings",
    "menu.groupWork": "Daily work",
    "menu.groupEmployees": "Employees",
    "menu.groupReports": "Reports",
    "menu.groupSystem": "System",
    "menu.monthlyAccounting": "Monthly payroll",
    "menu.vacationTracker": "Vacation tracker",
    "dashboard.insideNow": "Inside now",
    "dashboard.todayEvents": "Today events",
    "dashboard.openDays": "Open days",
    "dashboard.activeEmployees": "Active employees",

    "common.actions": "Actions",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.yes": "Yes",
    "common.no": "No",

    "scan.title": "Manual entry",
    "scan.description": "Enter an employee code manually for check-in or check-out.",
    "scan.placeholder": "QR reader area",
    "scan.startCamera": "Start camera",
    "scan.stopCamera": "Stop camera",
    "scan.switchToFrontCamera": "Use front camera",
    "scan.switchToBackCamera": "Use rear camera",
    "scan.openStandalone": "Open Scan terminal",
    "scan.checkIn": "Check in",
    "scan.checkOut": "Check out",
    "scan.cancel": "Cancel",
    "scan.showQrCode": "Show the QR code to the camera",
    "scan.scanForIn": "Check in – show the QR code",
    "scan.scanForOut": "Check out – show the QR code",
    "scan.checkedIn": "Successfully checked in",
    "scan.checkedOut": "Successfully checked out",
    "scan.operationFailed": "Operation failed",
    "scan.serverSaveFailed": "Saving to the server failed. Please try again.",
    "scan.alreadyCheckedIn": "You are already checked in",
    "scan.alreadyCheckedOut": "You are already checked out",
    "scan.manualLabel": "Employee code",
    "scan.manualPlaceholder": "E.g. EMP-001",
    "scan.manualButton": "Save entry",
    "scan.statusReady": "Enter the employee code.",
    "scan.cameraRunning": "Camera started. Show the QR code to the camera.",
    "scan.cameraStopped": "Camera stopped.",
    "scan.cameraTimeout": "No code was scanned. The camera stopped.",
    "scan.cameraError": "The camera could not be started. Check permission and HTTPS connection.",
    "scan.secureContextError": "The camera does not work in file:// mode. HTTPS or a development server is required.",
    "scan.barcodeUnsupported": "This browser does not support native QR scanning.",
    "scan.codeRead": "QR code scanned.",
    "scan.codeNotFound": "No employee found for this code.",
    "scan.unknownCode": "Unknown employee code",
    "scan.sourceCamera": "Camera",
    "scan.sourceUsb": "USB QR reader",
    "scan.sourceManual": "Manual test",
    "scan.noResultTitle": "No employee recorded",
    "scan.noResultText": "Enter the employee code, then save the entry.",
    "kiosk.subtitle": "Attendance kiosk",
    "kiosk.readyTitle": "Ready to scan",
    "kiosk.readyText": "Hold the QR code in front of the reader.",
    "kiosk.checkedIn": "Checked in",
    "kiosk.checkedOut": "Checked out",

    "employees.title": "Employees",
    "employees.description": "Employees can be added and managed here.",
    "employees.empty": "No employees added yet.",

    "employee.code": "Employee code",
    "employee.name": "Name",
    "employee.namePlaceholder": "Employee name",
    "employee.department": "Department",
    "employee.departmentPlaceholder": "E.g. Production",
    "employee.active": "Active employee",
    "employee.lunchBreakEnabled": "Deduct lunch break",
    "employee.lunchBreakShort": "Lunch break",
    "employee.inactive": "Inactive",
    "employee.status": "Status",
    "employee.note": "Note",
    "employee.notePlaceholder": "Note",
    "employee.save": "Save employee",
    "employee.new": "New employee",
    "employee.updated": "Employee updated.",
    "employee.saved": "Employee saved.",
    "employee.deleted": "Employee deleted.",
    "employee.nameRequired": "Employee name is required.",
    "employee.deleteConfirm": "Are you sure you want to delete this employee?",

    "cards.title": "Print cards",
    "cards.description": "Two-sided 32 × 46 mm inserts: QR side and landscape information side.",
    "cards.refresh": "Refresh cards",
    "cards.print": "Print cards",
    "cards.selectAll": "Select all",
    "cards.clearSelection": "Clear selection",
    "cards.noSelection": "Select at least one employee card.",
    "cards.onlyActive": "Cards are created only for active employees.",
    "cards.empty": "There are no active employees. Add an employee on the Employees page first.",
    "cards.cardTitle": "Attendance card",
    "cards.qrInfo": "QR code access card",
    "cards.printError": "The print window did not open. Check if the browser blocked it.",

    "inside.title": "Currently inside",
    "inside.description": "This page will show who is currently inside.",

    "inside.empty": "Nobody is currently inside.",
    "inside.summary": "Currently inside",
    "inside.refresh": "Refresh",
    "inside.arrivalTime": "Arrival time",
    "inside.lastEvent": "Last event",

    "attendance.in": "Arrival",
    "attendance.out": "Departure",
    "attendance.date": "Date",
    "attendance.search": "Search",
    "attendance.searchPlaceholder": "Name, code or department",
    "attendance.today": "Today",
    "attendance.printDaily": "PDF / Print",
    "attendance.exportDailyXlsx": "XLSX",
    "attendance.printWeekly": "PDF / Print",
    "attendance.exportWeeklyXlsx": "XLSX",
    "attendance.printMonthly": "PDF / Print",
    "attendance.exportMonthlyXlsx": "XLSX",
    "attendance.exportPanelTitle": "Export / print",
    "attendance.exportGroupDaily": "Daily",
    "attendance.exportGroupWeekly": "Weekly",
    "attendance.exportGroupMonthly": "Monthly",
    "attendance.viewMode": "View",
    "attendance.viewDaily": "Daily",
    "attendance.viewWeekly": "Weekly",
    "attendance.viewMonthly": "Monthly",
    "attendance.empty": "No attendance events for this day.",
    "attendance.savedIn": "Arrival saved.",
    "attendance.savedOut": "Departure saved.",
    "attendance.inactiveNotSaved": "Attendance is not saved for inactive employees.",
    "attendance.eventType": "Type",
    "attendance.time": "Time",
    "attendance.source": "Source",
    "attendance.employee": "Employee",
    "attendance.code": "Code",
    "attendance.department": "Department",

    "attendance.dailySummaryTitle": "Daily summary by employee",
    "attendance.periodSummaryTitle": "Period summary by employee",
    "attendance.workDays": "Attendance days",
    "attendance.openDays": "Open days",
    "attendance.firstArrival": "Start time",
    "attendance.lastDeparture": "Departure time",
    "attendance.rawWorked": "Duration",
    "attendance.lunchDeduction": "Lunch break",
    "attendance.netWorked": "Worked time",
    "attendance.overtime": "Overtime",
    "attendance.missing": "Missing",
    "attendance.balance": "Balance",
    "attendance.dayStatus": "Status",
    "attendance.noSummary": "No daily summary for this day.",
    "attendance.noPeriodRows": "No daily breakdown for this period.",
    "attendance.noPeriodSummary": "No period summary for this period.",
    "attendance.statusClosed": "Closed",
    "attendance.statusOpen": "In progress",
    "attendance.statusIncomplete": "Incomplete",
    "attendance.openDayWarningOne": "Warning: {count} employee has no departure recorded.",
    "attendance.openDayWarningMany": "Warning: {count} employees have no departure recorded.",

    "attendance.editBoxTitle": "Edit daily arrival and departure",
    "attendance.saveCorrection": "Save arrival and departure",
    "attendance.eventsToCorrect": "Events to correct",
    "attendance.addArrival": "+ Add arrival",
    "attendance.addDeparture": "+ Add departure",
    "attendance.cancelCorrection": "Cancel",
    "attendance.eventUpdated": "Arrival and departure times saved.",
    "attendance.invalidTimeRange": "Departure time must be later than arrival time.",
    "attendance.invalidTimeFormat": "Enter time in 24-hour HH:MM format, for example 15:30.",
    "attendance.eventDeleted": "Attendance event deleted.",
    "attendance.deleteConfirm": "Are you sure you want to delete this attendance event?",
    "attendance.eventRequired": "Select an event to edit.",

    "attendance.title": "Attendance list",
    "attendance.description": "Daily, weekly and monthly attendance lists will be here.",

    "profile.title": "Employee profile",
    "profile.description": "Monthly attendance summary by employee.",
    "profile.employee": "Employee",
    "profile.search": "Search employee",
    "profile.searchPlaceholder": "Name, code or department",
    "profile.noSearchResults": "No results",
    "profile.month": "Month",
    "profile.refresh": "Refresh",
    "profile.printPdf": "Employee PDF / Print",
    "profile.exportXlsx": "Employee XLSX export",
    "profile.selectEmployee": "Select employee",
    "profile.noEmployees": "No employees added",
    "profile.noData": "No attendance data in this month.",
    "profile.workDays": "Attendance days",
    "profile.totalWorked": "Total worked time",
    "profile.totalBalance": "Total balance",
    "profile.openDays": "Open days",
    "profile.dailyRowsTitle": "Daily breakdown",
    "profile.eventRowsTitle": "Daily in/out movements",
    "profile.eventNumber": "No.",
    "profile.noEvents": "No in/out movements in this month.",

    "statistics.title": "Manager overview",
    "statistics.description": "Daily statuses and records requiring review.",
    "statistics.date": "Date",
    "statistics.today": "Today",
    "statistics.refresh": "Refresh",
    "statistics.totalEmployees": "Total employees",
    "statistics.activeEmployees": "Active employees",
    "statistics.employeesWithEvents": "Employees with events",
    "statistics.currentlyInside": "Currently inside",
    "statistics.closedDays": "Closed days",
    "statistics.openDays": "In progress",
    "statistics.totalWorked": "Total worked time",
    "statistics.totalBalance": "Total balance",
    "statistics.dailyTableTitle": "Daily status of active employees",
    "statistics.noData": "No attendance data for this day.",
    "statistics.arrived": "Arrived",
    "statistics.leftToday": "Left",
    "statistics.absentToday": "Registered absence",
    "statistics.notArrived": "Not arrived",
    "statistics.needsAttention": "Needs review",
    "statistics.attentionTitle": "Needs attention",
    "statistics.issue": "Issue",
    "statistics.noIssues": "No records require review.",
    "statistics.statusInside": "Inside",
    "statistics.statusLeft": "Left",
    "statistics.statusAbsent": "Absent",
    "statistics.statusNotArrived": "Not arrived",
    "statistics.statusNoEntry": "No entry",
    "statistics.invalidOrder": "Invalid arrival/departure order",
    "statistics.absenceConflict": "Absence and attendance recorded on the same day",
    "statistics.forgottenDeparture": "Departure probably forgotten",
    "statistics.shortWorkday": "Short closed workday",
    "statistics.noArrivalOrAbsence": "No arrival or absence recorded",
    "statistics.statusDayOff": "Day off",
    "statistics.upcomingAbsences": "Current and upcoming absences",
    "statistics.noUpcomingAbsences": "No absences are recorded for the next 7 days.",
    "statistics.monthlyLeaders": "Monthly highlighted differences",
    "statistics.mostOvertime": "Most overtime",
    "statistics.mostMissing": "Most missing time",
    "statistics.noRankingData": "No data to display.",

    "monthly.title": "Monthly payroll",
    "monthly.description": "Monthly overview for 100+ employees with worked time, overtime, meal vouchers and absences.",
    "monthly.summaryTitle": "Monthly overview",
    "monthly.detailTitle": "Employee monthly details",
    "monthly.absenceFormTitle": "Record absence",
    "monthly.absenceListTitle": "Monthly absences",
    "monthly.details": "Details",
    "monthly.noRows": "No employees to show in this view.",
    "monthly.noDetails": "No attendance or absence data for this employee in this month.",
    "monthly.selectEmployee": "Choose an employee from the monthly table.",

    "vacation.title": "Vacation tracker",
    "vacation.description": "Track annual allowance, used days and future bookings.",
    "vacation.year": "Year",
    "vacation.allDepartments": "All departments",
    "vacation.allowanceTitle": "Set annual vacation allowance",
    "vacation.entitled": "Annual allowance",
    "vacation.carried": "Carried-over days",
    "vacation.available": "Total available",
    "vacation.used": "Used days",
    "vacation.booked": "Booked days",
    "vacation.remaining": "Remaining days",
    "vacation.nextDate": "Next vacation",
    "vacation.saveAllowance": "Save allowance",
    "vacation.statusReady": "Vacation tracker is ready.",
    "vacation.saved": "Vacation allowance saved.",
    "vacation.invalidAllowance": "Choose an employee and enter valid non-negative values.",
    "vacation.overviewTitle": "Employee vacation allowances",
    "vacation.detailsTitle": "Vacation details",
    "vacation.workdays": "Counted workdays",
    "vacation.periodStatus": "Status",
    "vacation.usedStatus": "Used",
    "vacation.bookedStatus": "Booked",
    "vacation.currentStatus": "Current",
    "vacation.noRows": "No employees to display.",
    "vacation.noDetails": "No vacation is recorded for this employee in this year.",
    "vacation.selectEmployee": "Choose an employee from the table.",

    "absence.startDate": "Start date",
    "absence.endDate": "End date",
    "absence.type": "Absence type",
    "absence.sick": "Sick leave",
    "absence.vacation": "Vacation",
    "absence.excused": "Excused absence",
    "absence.unexcused": "Unexcused absence",
    "absence.unpaid": "Unpaid leave",
    "absence.other": "Other",
    "absence.sickShort": "Sick",
    "absence.vacationShort": "Vac.",
    "absence.excusedShort": "Excused",
    "absence.unexcusedShort": "Unexcused",
    "absence.unpaidShort": "Unpaid",
    "absence.otherShort": "Other",
    "absence.totalDays": "Absence days",
    "absence.save": "Save absence",
    "absence.invalid": "Choose an employee and a valid date range.",
    "absence.empty": "No absences recorded for this month.",
    "absence.deleteConfirm": "Delete this absence?",

    "export.title": "Export / Import",
    "export.description": "JSON backup and restore for localStorage data.",
    "export.jsonTitle": "JSON backup / restore",
    "export.jsonDescription": "The JSON backup contains settings, employees and attendance events.",
    "export.importWarning": "Warning: restoring will overwrite the current data.",
    "export.downloadJson": "Download JSON backup",
    "export.importJson": "Restore JSON",
    "export.statusReady": "Export / Import ready.",
    "export.summarySettings": "Settings",
    "export.summaryEmployees": "Employees",
    "export.summaryEvents": "Attendance events",
    "export.saved": "JSON backup downloaded.",
    "export.xlsxSaved": "XLSX export downloaded.",
    "export.xlsxError": "XLSX export failed.",
    "export.importNoFile": "No JSON file selected.",
    "export.importInvalid": "Invalid or incompatible JSON file.",
    "export.importConfirm": "Are you sure you want to restore this backup? Current data will be overwritten.",
    "export.importSuccess": "JSON backup restored successfully.",
    "export.importError": "JSON restore failed.",

    "print.dailyAttendanceTitle": "Daily attendance list",
    "print.weeklyAttendanceTitle": "Weekly attendance list",
    "print.weekRange": "Week range",
    "print.weeklySummary": "Weekly summary by employee",
    "print.monthlyAttendanceTitle": "Monthly attendance list",
    "print.employeeAttendanceTitle": "Employee attendance sheet",
    "print.employeePeriod": "Period",
    "print.employeeSummary": "Employee summary",
    "print.employeeDailyBreakdown": "Daily breakdown",
    "print.employeeNoData": "No attendance data for this employee in this month.",
    "print.monthRange": "Month range",
    "print.monthlySummary": "Monthly summary by employee",
    "print.monthlyDailyBreakdown": "Daily breakdown in the month",
    "print.noMonthlySummary": "No monthly attendance data in this period.",
    "print.weeklyDailyBreakdown": "Daily breakdown in the week",
    "print.workDays": "Attendance days",
    "print.openDays": "Open days",
    "print.awayTime": "Away time",
    "print.noWeeklySummary": "No weekly attendance data in this period.",
    "print.generatedAt": "Print time",
    "print.company": "Company",
    "print.dailyEvents": "Daily events",
    "print.dailySummary": "Daily summary by employee",
    "print.noEvents": "No attendance events for this day.",
    "print.noSummary": "No daily summary for this day.",
    "print.printError": "The print window did not open. Check if the browser blocked it.",

    "settings.title": "Settings",
    "settings.companyName": "Company name",
    "settings.dailyNorm": "Daily norm",
    "settings.lunchBreak": "Lunch break",
    "settings.overtimeHourlyRate": "Overtime hourly rate (lei/hour)",
    "settings.showOvertimeData": "Show overtime and overtime pay",
    "settings.mealVoucherDailyValue": "Meal voucher value (lei/day)",
    "settings.storageMode": "Storage mode",
    "settings.save": "Save settings",
    "settings.reset": "Reset defaults",
    "settings.statusReady": "Settings are ready.",
    "settings.saved": "Settings saved.",
    "settings.resetDone": "Defaults restored.",
    "settings.invalidDailyNorm": "Daily norm must be at least 01:00.",
    "settings.invalidLunchBreak": "Lunch break cannot be longer than the daily norm.",
    "settings.invalidPaymentValues": "Overtime rate and meal voucher value cannot be negative.",

    "payment.overtimeRate": "Overtime hourly rate",
    "payment.overtimeValue": "Overtime value",
    "payment.mealVoucherDailyValue": "Meal voucher daily value",
    "payment.mealVoucherDays": "Meal voucher days",
    "payment.mealVoucherValue": "Meal voucher value",
    "payment.totalPayment": "Total payment",
    "absence.allActiveEmployees": "All active employees",
    "calendar.title": "Company work calendar",
    "calendar.dayType": "Day type",
    "calendar.dayOff": "Day off",
    "calendar.vacation": "Vacation",
    "calendar.save": "Save period",
    "calendar.invalid": "Select a valid start and end date.",
    "calendar.empty": "There are no company days off or vacation periods in this month.",
    "calendar.deleteConfirm": "Are you sure you want to delete this period?",

    "backup.closeWarning": "Before closing, the data will be saved automatically.",
    "backup.restoreAutoBackup": "Restore automatic backup",
    "backup.restoreConfirm": "Are you sure you want to restore the latest automatic backup? Current data will be overwritten.",
    "backup.restoreMissing": "No automatic backup is available.",
    "backup.restoreInvalid": "The automatic backup is invalid or cannot be read.",
    "backup.restoreSuccess": "Automatic backup restored successfully.",
    "backup.restoreError": "Automatic backup restore failed.",
  }
};



